name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "ARM64"]
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true
        tags: hyuabot-api-server-python:latest
    - name: Rollout dev python backend pod
      run: |
        kubectl -n hyuabot-prod rollout restart deployment/hyuabot-api-python-development
