name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "ARM64"]
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    env:
      IMAGE_NAME: localhost:32000/hyuabot/hyuabot-api-server-python:latest
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    steps:
    - name: Env setup
      run: |
        echo "JWT_ALGORITHM=HS256" >> .env
        echo "JWT_EXPIRATION=21000" >> .env
        echo "JWT_SECRET_KEY=SECRET" >> .env
        echo "SITE_DOMAIN=api.hyuabot.app" >> .env
        echo "ENVIRONMENT=production" >> .env
        echo "CORS_HEADERS=[\"*\"]" >> .env
        echo "CORS_ORIGINS=[\"https://*.hyuabot.app\"]" >> .env
        echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env
        echo "REDIS_URL=${{ env.REDIS_URL }}" >> .env
        echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ env.POSTGRES_DB }}" >> .env
        echo "POSTGRES_HOST=${{ env.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_PORT=${{ env.POSTGRES_PORT }}" >> .env
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.IMAGE_NAME }}
        no-cache: true
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}
