name: deploy

on:
  pull_request:
    branches:
    - main
    types:
    - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "ARM64"]
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    env:
      IMAGE_NAME: localhost:5000/hyuabot-api-server-python:latest
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      REDIS_URL: ${{ secrets.PROD_REDIS_URL }}
      POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.PROD_POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.PROD_POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.PROD_POSTGRES_PORT }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.IMAGE_NAME }}
        no-cache: true
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}
