name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.5 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_SECRET}}
          heroku_app_name: "hyuabot" #Must be unique in Heroku
          heroku_email: "jil8885@hanyang.ac.kr"
          buildpack: "" #OPTIONAL
          branch: "master" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: false #OPTIONAL and DEFAULT - false
          appdir: "" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder
          docker_heroku_process_type: "" #OPTIONAL and DEFAULT - "web"
